### PR TITLE
Fixed #50, Changed non hover text color of Apply button on Homepage

### LINKED ISSUE #50: Homepage Apply button is not visible when not hovered
The APPLY button on the homepage is visually discouraging. The color of the button and text are too similar. Thus seeing or noticing the button is difficult.

I can try to fix this if you would like...

Assign me the task if you permit.

### PR DESCRIPTION
**Pull request by Arghya-Banerjee**
Changed non-hover text color of apply now button to white to have better visibility

## General Checks

- [x] the branch is up to date with `main`/`master`
- [x] the code works when pulled and run locally
- [x] All CI checks pass
- [x] all conflicts are resolved (if any)
- [x] PR has a descriptive title
- [x] PR has appropriate labels and milestones for easy identification
- [x] PR it is assigned to the owner
- [x] reviewers are assigned
- [x] the PR contributes only one focused change
- [x] It is in the appropriate column in the project board (if necessary)
- [x] has short and clear description
- [x] is linked to an issue (if it is related)
- [x] feedback is addressed (if any and if it is appropriate feedback.)

## Markdown

- [x] the markdown source is formatted
- [x] spelling and grammar is correct in all text
- [x] The markdown looks correct when you preview the file
- [x] all links and images work

### HTML

- [x] pages besides `/index.html` are stored in `/pages`
- [x] the code is well-formatted
- [x] the HTML is valid
- [x] there are no inline styles (example: `style='color: red;'`)
- [x] there are no `<style>` tags with CSS, all styles are hrefs
- [x] there is no inline JavaScript (example: `onclick='doSomething()'`)
- [x] there are no `<script>` tags with JS, all JS is in an separate file
- [x] `id`s are used for JavaScript only, not for CSS
- [x] semantic tags are used
- [x] spelling and grammar is correct in all site content

### CSS

- [x] the code is well-formatted
- [x] passes all the linting checks

### CODE REVIEW

**Comment by galalkoro98** [comment]
@Arghya-Banerjee  well done but could ou please run 
1. `npm run format` 
2. `npm run format:check`
 3. `npm run lint:css`
screenshoot

**Comment by Arghya-Banerjee** [comment]
Yeah I will check just after college

**Comment by Arghya-Banerjee** [comment]
Sir I have checked all 3 of the tests that you mentioned above and none of them failed. I am attaching the full terminal operation message 

```
...\agile-development-hyf-group-2> npm run format

> template-html-css@1.0.0 format
> prettier --write ./

.achecker.yml 101ms
.cspell.json 212ms
.github\ISSUE_TEMPLATE\help-wanted.md 98ms
.github\ISSUE_TEMPLATE\question.md 6ms
.github\pull_request_template.md 43ms
.github\workflows\lint-and-validate.yml 16ms
.htmlvalidate.json 51ms
.ls-lint.yml 13ms
.markdownlint.jsonc 43ms
.prettierrc.json 14ms
.stylelintrc.json 7ms
.vscode\settings.json 3ms
CODE-OF-CONDUCT.md 100ms
CONTRIBUTING.md 2ms
index.html 201ms
package-lock.json 184ms
package.json 2ms
pages\about.html 17ms
pages\digitalents.html 41ms
pages\faq.html 30ms
pages\program.html 22ms
pages\README.md 10ms
pages\support.html 18ms
pages\volunteer.html 25ms
planning\backlog.md 40ms
planning\communication-plan.md 51ms
planning\constraints.md 13ms
planning\design.md 8ms
planning\development-strategy.md 69ms
planning\README.md 64ms
planning\retrospective.md 2ms
public\README.md 11ms
README.md 84ms
styles\about.css 158ms
styles\digitalents.css 48ms
styles\faq.css 43ms
styles\index.css 139ms
styles\README.md 8ms
styles\something.css 24ms
styles\support.css 30ms
styles\volunteer.css 30ms

> template-html-css@1.0.0 format:check
> prettier --check ./

Checking formatting...
All matched files use Prettier code style!


...\agile-development-hyf-group-2> npm run lint:css

> template-html-css@1.0.0 lint:css
> stylelint ./**/*.css

...\agile-development-hyf-group-2> npm run lint:css

> template-html-css@1.0.0 lint:css
> stylelint ./**/*.css

...\agile-development-hyf-group-2> 
```

**Comment by galalkoro98** [comment]
> Sir I have checked all 3 of the tests that you mentioned above and none of them failed. I am attaching the full terminal operation message
> 
> ```
> ...\agile-development-hyf-group-2> npm run format
> 
> > template-html-css@1.0.0 format
> > prettier --write ./
> 
> .achecker.yml 101ms
> .cspell.json 212ms
> .github\ISSUE_TEMPLATE\help-wanted.md 98ms
> .github\ISSUE_TEMPLATE\question.md 6ms
> .github\pull_request_template.md 43ms
> .github\workflows\lint-and-validate.yml 16ms
> .htmlvalidate.json 51ms
> .ls-lint.yml 13ms
> .markdownlint.jsonc 43ms
> .prettierrc.json 14ms
> .stylelintrc.json 7ms
> .vscode\settings.json 3ms
> CODE-OF-CONDUCT.md 100ms
> CONTRIBUTING.md 2ms
> index.html 201ms
> package-lock.json 184ms
> package.json 2ms
> pages\about.html 17ms
> pages\digitalents.html 41ms
> pages\faq.html 30ms
> pages\program.html 22ms
> pages\README.md 10ms
> pages\support.html 18ms
> pages\volunteer.html 25ms
> planning\backlog.md 40ms
> planning\communication-plan.md 51ms
> planning\constraints.md 13ms
> planning\design.md 8ms
> planning\development-strategy.md 69ms
> planning\README.md 64ms
> planning\retrospective.md 2ms
> public\README.md 11ms
> README.md 84ms
> styles\about.css 158ms
> styles\digitalents.css 48ms
> styles\faq.css 43ms
> styles\index.css 139ms
> styles\README.md 8ms
> styles\something.css 24ms
> styles\support.css 30ms
> styles\volunteer.css 30ms
> 
> > template-html-css@1.0.0 format:check
> > prettier --check ./
> 
> Checking formatting...
> All matched files use Prettier code style!
> 
> 
> ...\agile-development-hyf-group-2> npm run lint:css
> 
> > template-html-css@1.0.0 lint:css
> > stylelint ./**/*.css
> 
> ...\agile-development-hyf-group-2> npm run lint:css
> 
> > template-html-css@1.0.0 lint:css
> > stylelint ./**/*.css
> 
> ...\agile-development-hyf-group-2> 
> ```

@Arghya-Banerjee I can see everything is passed but you just have to check your changes and then pushed again.

**Comment by Arghya-Banerjee** [comment]
Sir do you want me to create a new pull request then?

**Comment by galalkoro98** [comment]
> Sir do you want me to create a new pull request then?

no you do not have, the same pull request, jsut on you terminal check the status of repository if there is some changes commit and push

**Comment by Arghya-Banerjee** [comment]
> > Sir do you want me to create a new pull request then?
> 
> no you do not have, the same pull request, jsut on you terminal check the status of repository if there is some changes commit and push

Sir, I have committed some of the leftover changes that you requested. If there are still some discrepancies please inform me

**Comment by galalkoro98** [comment]
> > > Sir do you want me to create a new pull request then?
> > 
> > 
> > no you do not have, the same pull request, jsut on you terminal check the status of repository if there is some changes commit and push
> 
> Sir, I have committed some of the leftover changes that you requested. If there are still some discrepancies please inform me

@Arghya-Banerjee  well done all check have passed and now I can esaly merge it.

**Review by galalkoro98 — APPROVED** [review]

**Pull request merged**
